name: PHP Coding Standards Fixer
on:
  pull_request:
  push:
    branches:
    - qa/**
    - stable/**
jobs:
  php-cs-fixer:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # TODO: actions/cache@v1
    - name: Install dependencies
      run: composer update
    - name: Run php-cs-fixer
      run: php vendor/composer/bin/php-cs-fixer fix --dry-run --diff --using-cache=no
